schema {
  query: Query
}

type Query {
  # Получить информацию о клиенте по ID
  client(id: ID!): Client
}

# Клиент
type Client {
  id: ID!
  name: String
  age: Int
  documents: [Document]
  relatives: [Relative]
}

# Документ клиента
type Document {
  id: ID!
  type: String
  number: String
  issueDate: String
  expiryDate: String
}

# Родственник клиента
type Relative {
  id: ID!
  relationType: String
  name: String
  age: Int
}
